---
- hosts: all
  gather_facts: yes
  become: yes
  tasks:
        - name: "Update Cache"
          apt:
              update_cache: yes

- hosts: HAproxy
  become: yes
  tasks:
          - name: "Installing haproxy"
            package:
                    name: "haproxy"
                    state: present


          - name: "Copying configuration file"
            template:
                    src: "haproxy.cfg.j2"
                    dest: "/etc/haproxy/haproxy.cfg"


          - name: "starting haproxy services"
            service:
                    name: "haproxy"
                    state: started


- name: Configure Flask Web Server
  hosts: webservers
  become: true
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install pip3
      apt:
        name: python3-pip
        state: present
        update_cache: true

    - name: Install Gunicorn
      apt:
        name: gunicorn

    - name: Copy Python file to app.py
      copy:
         src: /$PWD/app1.py
         dest: /home/ubuntu/app1.py
         owner: ubuntu
         mode: '0644'

    - name: Run Flask app
      shell: gunicorn -w 2 -D -b 0.0.0.0:8000 app1:app
- hosts: HAproxy
  become: yes
  tasks:

          - name: "starting haproxy services"
            service:
                    name: "haproxy"
                    state: started
