######################## /etc/ansible/site.yaml##################################
---
- hosts: HAproxy
  become: true
  tasks:
    - name: Install HAProxy
      apt:
        name: haproxy
        state: latest

    - name: Configure HAProxy
      copy:
        src: /haproxy.cfg
        dest: /etc/haproxy/haproxy.cfg
      notify:
        - Restart HAProxy

    - name: Start HAProxy
      service:
        name: haproxy
        state: started
        enabled: true

  handlers:
    - name: Restart HAProxy
      service:
        name: haproxy
        state: restarted

- name: Create Flask App directory and virtual environment
  hosts: webservers
  become: true
  tasks:
    - name: Create Flask App directory
      file:
        path: /home/ubuntu/flask-app
        state: directory

    - name: Create virtual environment
      command: python3 -m venv /home/ubuntu/flask-app/venv
      become: yes
      args:
        chdir: /home/ubuntu/flask-app

    - name: Activate virtual environment
      command: /bin/bash -c "source /home/flask-app/venv/bin/activate"
      args:
        chdir: /home/ubuntu/flask-app

    - name: Install Flask
      pip:
        name: Flask
        virtualenv: /home/ubuntu/flask-app/venv
    - name: Copy flask app to remote server
      become: yes
      copy:
        src: /app.py
        dest: /home/ubuntu/flask-app/venv

    - name: Start flask app
      become: yes
      shell: |
        cd /home/ubuntu/flask-app/
        source venv/bin/activate
        nohup python3 app.py &

                                                                                                     
